version: '3.8'

services:
  web:
    build: .
    ports:
      - "7755:7755"
    environment:
      FLASK_APP: core/server.py
      GUNICORN_PORT: 7755
      GUNICORN_LOG_LEVEL: debug
    command: gunicorn -c gunicorn_config.py core.server:app
    volumes:
      - .:/core
